### ISSUE TITLE
Wrong discuss link in the extension page

### ISSUE THREAD

**Issue by PeopleInside** [blomstra/flarum-ext-database-queue#1]
Once the extension database queue is installed, if you open the relative extension page and click on discuss link, the link seems point to a not correct discuss discussion.

The wrong link point to https://discuss.flarum.org/d/21873-redis-sessions-cache-queues
The correct link should be: https://discuss.flarum.org/d/28151-database-queue-the-simplest-queue-even-for-shared-hosting

![immagine](https://github.com/blomstra/flarum-ext-database-queue/assets/5006150/b348bf4f-8857-4622-96ce-dbd83287d9cf)

**Comment by luceos** [comment]
Thank you. Needs a new version, but is patched.
